%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=jdbc:h2:file:./data/labzeiss_db;AUTO_SERVER=TRUE
%dev.quarkus.hibernate-orm.schema-management.strategy=update
%dev.quarkus.hibernate-orm.log.sql=true

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

app.seed.admin.senha=reputation

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,PUT,POST,DELETE,PATCH,OPTIONS
quarkus.http.cors.headers=authorization,content-type
quarkus.http.cors.exposed-headers=authorization
quarkus.http.cors.access-control-allow-credentials=true

mp.jwt.token.header=Cookie
mp.jwt.token.cookie=jwt-token
mp.jwt.verify.issuer=cem-senai-zeiss
